artikel/urls.py
from . import views
from django.urls import path

app_name = "artikel"

urlpatterns = [
    path('artikel/', views.artikelPage, name='home'),
    path('artikel/<slug:slug>/', views.formCom, name='post_detail'),
]

pesan/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'pesan'

urlpatterns = [
    path('pesan/', views.home, name='home'),
    path('datas/', views.experience, name='isi'),
    path('res/', views.hasil, name='res'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('feedback.urls')),
    path('',include('produk.urls')),
    path('', include('pesan.urls')),
    path('', include('artikel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artikel/models.py
from django.db import models

# Create your models here.
STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author =  models.CharField(max_length=200, unique=True)
    image = models.ImageField(null=True, blank=True)
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except :
            url = ''
        return url
    
    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class Comment(models.Model):
    uname = models.CharField(max_length=30)
    com = models.TextField()
    post_com = models.ForeignKey(Post,on_delete=models.CASCADE,null=True)

artikel/forms.py
from django import forms
from .models import Comment

class Form_Comment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['uname', 'com']

    error_messages = {
        'required' : 'Tolong diisi'
    }
    
    uname_attrs = {
        'type':'text',
        'class':"form-control",
        'placeholder':'Username'
    }
    
    com_attrs = {
        'type':'text',
        'class':"form-control",
        'placeholder':'Tuliskan Komentarmu Disini!'
    }

    uname = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=uname_attrs))
    com = forms.CharField(label='', required=True, max_length=200, widget=forms.Textarea(attrs=com_attrs))

artikel/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect
from .forms import Form_Comment
from .models import Post, Comment
# Create your views here.
def artikelPage(request):
    post =  Post.objects.filter(status=1)
    response = {
        'object_list': post,
    }
    return render(request, 'artindex.html', response)



def formCom(request,slug):
    post = Post.objects.get(slug=slug)
    comments = Comment.objects.filter(post_com=post)
    form = Form_Comment(request.POST or None)
    if (form.is_valid and request.method == "POST"):
        new_comment = Comment(post_com=Post.objects.get(slug=slug), uname=form.data['uname'], com=form.data['com'])
        new_comment.save()
        return HttpResponseRedirect('/artikel')
    response = {
        'post': post,
        'input_form': Form_Comment,
        'comments': comments
    }
    return render(request, 'post_detail.html', response)

artikel/templates/artindex.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .header {
        color: #37676E;
        padding-left: 120px;
    }
    .header h1 {
        font-weight: bolder;
        padding-top: 50px;
        font-size: 90px;}
    .header span {
        color: #B91A00
    }
    .header h6 {
        font-size: 22px;
    }

    .btn-default{
    background-color: #37676E;
    color:#FFF;
    border-color: #2F3E48;
    }
  
    .btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open .dropdown-toggle.btn-default {   
    background-color: #BF3939;
    color:#FFF;
    border-color: #31347B;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>
<head>
    <title>Artikel</title>
</head>
<body>
    <div class="col-12 header">
        <h1>ARTI<span>KEL</span></h1>
        <h6>Yang perlu kalian baca lebih lanjut!</h6>
    </div>
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for post in object_list %}
                <div class="card mb-4">
                    <div class="card-body">
                        {% if post.image %}
                        <img src="{{ post.imageURL }}" style="width:300px; padding-bottom: 10px;">
                        {% elif post.image is None %}
                        <p>&nbsp;</p>
                        {% endif %}
                        <h2 class="card-title">{{ post.title }}</h2>
                        <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                        <p class="card-text">{{post.content|slice:":200" }}...</p>
                        <a href="{% url 'artikel:post_detail' post.slug  %}" class="btn btn-default">Baca Lebih Lanjut &rarr;</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>

{%endblock%}

artikel/templates/post_detail.html
{% extends 'base.html' %} {% block content %}
<style>
  .btn-default{
    background-color: #37676E;
    color:#FFF;
    border-color: #2F3E48;
    }
  
    .btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open .dropdown-toggle.btn-default {   
    background-color: #BF3939;
    color:#FFF;
    border-color: #31347B;
    }


</style>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-8 card mb-4  mt-3 left top">
        <div class="card-body">
          {% if post.image %}
          <img src="{{ post.imageURL }}" style="width:500px; padding-bottom: 20px;">
          {% elif post.image is None %}
          <p>&nbsp;</p>
          {% endif %}
          <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
          <p class="text-muted">{{ post.author }} | {{ post.created_on }}</p>
          <p class="card-text ">{{ post.content | safe }}</p>
        </div>
      </div>
    </div>
    <h3 style="padding-bottom: 20px;">Komentar Terbaru</h3>
    {% for comment in comments %}
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ comment.uname }}</h5>
          <p class="card-text">{{ comment.com }}</p>
        </div>
      </div>
      <p>&nbsp;</p>
    {% endfor %}
    <h3 style="padding-bottom: 20px;">Tulis Komentarmu!</h3>
    <form action='' method="POST">
      {% csrf_token %}
      {{ input_form.as_p }}
       <button type="submit" class="btn btn-default">Submit</button>
    </form> 
  </div>
  {% endblock content %}
</body>